# -*- coding: utf-8 -*-
"""advertising_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rJEGRjFHy3atsOc2VT5I3NiKTyzLgN4T
"""

!pip install boto3

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


import boto3
import pandas as pd
import joblib
from io import StringIO

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Create S3 client
s3 = boto3.client('s3',
    aws_access_key_id="AKIATEKYFOX5LWJ5P7PU",
    aws_secret_access_key="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",
    region_name="ap-southeast-1")

# Read CSV directly into pandas (without downloading)
response = s3.get_object(Bucket='teamolducsyersproject', Key='processed/advertising.csv')
advertising_data = pd.read_csv(response['Body'])
print("Data loaded directly into pandas:")
print(advertising_data.head())

if advertising_data is not None:
    # Assuming your CSV has columns: TV, Radio, Newspaper, Sales
    # Adjust column names to match your actual data
    X = advertising_data[['TV', 'Radio', 'Newspaper']]  # Features
    y = advertising_data['Sales']  # Target variable

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R² Score: {r2:.4f}")

# 6. Save model (as requested)
    joblib.dump(model, 'advertising_model.joblib')
    print("Model saved as 'advertising_model.joblib'")